### ISSUE TITLE
lib/math/Mat.h merge

### ISSUE THREAD

**Issue by d3rky** [dmitryikh/nla3d#5]
Hi!

Please, tell me. Why do you have dMat and MatSym separate classes? Do I need to merge them too? Maybe they must be hidden behind one interface?

**Comment by dmitryikh** [comment]
@d3rky, MatSym is a symmetric dense matrix.For example, a matrix like this 
```
{{1,2,3},
 {2,4,5},
 {3,5,6}}
```
will be stored in MatSym like
```
{1,2,3,4,5,6}
```

For now, MatSym is primarly used to store finite element stiffness matrices. You can note that this is templated class, all the time we know exactly the size of element stiffness matrix, thats why.

What about dMat it's just a usual row oriented matrix with dynamical dimensions defined in runtime. 
You can grep a whole project and find out that dMat isn't used in nla3d. So, I think we can just drop dMat from nla3d (just move the source to trash folder, it will be seen later what to do with this code).

**Comment by dmitryikh** [comment]
@d3rky , you can found the tests for math::Mat and math::Vec classes in ```test/mat_math.cpp```.
You can found in elements/*.cpp source code and in FEStorage.cpp usages of Mat/Vec classes and decide which functionality we need to maintain in these classes.

**Comment by d3rky** [comment]
Ok, thanks.

P.S. For trash code there is another perfect place - history in version control system =)

**Comment by dmitryikh** [comment]
The main problem with ```math::Mat<dimM, dimN>``` class is that it stores data as an array of Vec<dimN> objects. And if we do something like this:
```
Mat<3,3> mat;
mat[0][0] = 1.0;
```

Actually we call Mat::operator[], then receive Vec<3> object and call Vec::operator[] to reciev a double&. This is overhead in my opinion. That's why here is ```math::Mat2<dimM, dimN>``` class where data are stored as simple as:
```
double data[dimM][dimN];
```
That should work faster (but I don't remember that I didi any benchmark on it). The problem that for ```math::Mat2``` here are just a few methods implemented (just a minimum of them that really need in nla3d code).

The idea is to "copy" all functionality from Mat to Mat2, then drop Mat :) But we also need to have MatSym as soon as many matrices in FEM are symmetric and we need an efficient data type for them.

**Comment by d3rky** [comment]
Ok, I'll think about the realization and architecture of the solution ;-)
